apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - repositories.yaml
  - mimir.yaml
  - loki.yaml
  - tempo.yaml
  - grafana.yaml
  - alloy.yaml
  - alertmanager.yaml
